# Temas avanzados {#sec-advanced-topics .unnumbered}

```{r}
#| echo: false
#| message: false
#| results: asis
source("common.R")
```

A medida que adquiera más fluidez en ggplot2, es posible que desee utilizarlo de formas más avanzadas. Es posible que desee escribir sus propias funciones que creen gráficos de forma reutilizable, o puede que desee escribir sus propios paquetes que extiendan ggplot2. Si esto lo describe a usted, entonces los capítulos de esta parte del libro están diseñados para ayudarlo a comenzar. En @sec-programming analizamos técnicas de programación que puede utilizar para crear visualizaciones de ggplot2 flexibles y reutilizables. A esto le sigue @sec-internals, que profundiza en la mecánica de lo que hace ggplot2 al crear un gráfico, y @sec-extensions, que se basa en esta discusión para hablar sobre cómo se escriben las extensiones de ggplot2. Finalmente, para concretar un poco más estas ideas, @sec-spring1 presenta un ejemplo práctico del desarrollo de una extensión ggplot2.
